######################################################################
# Automatically generated by qmake (2.01a) ven. juin 2 01:27:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              include \
              src \
              lib/rapidxml-1.13 \
              lib/craigsapp-midifile-5a7dc97/include \
              lib/craigsapp-midifile-5a7dc97/src-library \
              lib/craigsapp-midifile-5a7dc97/src-programs
INCLUDEPATH += . \
               lib/rapidxml-1.13 \
               lib/craigsapp-midifile-5a7dc97/include \
               include \
               src

# Input
HEADERS += include/chaine_markov.h \
           include/main_window.h \
           include/note.h \
           lib/rapidxml-1.13/rapidxml.hpp \
           lib/rapidxml-1.13/rapidxml_iterators.hpp \
           lib/rapidxml-1.13/rapidxml_print.hpp \
           lib/rapidxml-1.13/rapidxml_utils.hpp \
           lib/craigsapp-midifile-5a7dc97/include/Binasc.h \
           lib/craigsapp-midifile-5a7dc97/include/MidiEvent.h \
           lib/craigsapp-midifile-5a7dc97/include/MidiEventList.h \
           lib/craigsapp-midifile-5a7dc97/include/MidiFile.h \
           lib/craigsapp-midifile-5a7dc97/include/MidiMessage.h \
           lib/craigsapp-midifile-5a7dc97/include/Options.h \
           src/chaine_markov.tpp
SOURCES += src/convertir_musicxml.cpp \
           src/epurer_midi.cpp \
           src/epurer_musicxml.cpp \
           src/main.cpp \
           src/main_window.cpp \
           src/modeliser.cpp \
           src/note.cpp \
           src/validation_melodie_generee.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/Binasc.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/MidiEvent.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/MidiEventList.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/MidiFile.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/MidiMessage.cpp \
           lib/craigsapp-midifile-5a7dc97/src-library/Options.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/80off.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/asciimidi.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/binasc.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/createmidifile.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/createmidifile2.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/drumtab.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/durations.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/henonfile.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/mid2hum.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/mid2mat.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/mid2mtb.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/mid2svg.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2beep.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2binasc.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2melody.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2notes.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2skini.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midi2text.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midicat.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midiexcerpt.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/midimixup.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/miditime.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/peep2midi.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/perfid.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/shutak.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/smfdur.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/stretch.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/sysextest.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/text2midi.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/textmidi.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/toascii.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/tobin.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/tobinary.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/todec.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/tohex.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/type0.cpp \
           lib/craigsapp-midifile-5a7dc97/src-programs/vlv.cpp
